DROP TABLE IF EXISTS `Advisor`;
CREATE TABLE IF NOT EXISTS `Advisor` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Username` VARCHAR(64) NOT NULL,
	`Password` Char(255) NOT NULL,
	`Salt` CHAR(32) NOT NULL,
	PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `Appointment`;
CREATE TABLE IF NOT EXISTS `Appointment` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`StartTime` TIME NOT NULL,
	`Type` CHAR(1) NOT NULL,
	`Location` VARCHAR(64) NOT NULL,
	`Date` DATE NOT NULL,
	PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `AdvisorAppt`;
CREATE TABLE IF NOT EXISTS `AdvisorAppt` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`AdvisorID` INT NOT NULL,
	`ApptID` INT NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX `AdvisorId_idx` (`AdvisorID` ASC),
	INDEX `ApptId_idx` (`ApptID` ASC),
	CONSTRAINT `AdvisorID_FK`
		FOREIGN KEY (`AdvisorID`)
		REFERENCES `Advisor` (`ID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
	CONSTRAINT `ApptID_FK`
		FOREIGN KEY (`ApptID`)
		REFERENCES `Appointment` (`ID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS `Student`;
CREATE TABLE IF NOT EXISTS `Student` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(64) NOT NULL,
  `LastName` VARCHAR(64) NOT NULL,
  `StudentID` CHAR(7) NOT NULL,
  `Email` VARCHAR(64) NOT NULL,
  `Major` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `StudentAppt`;
CREATE TABLE IF NOT EXISTS `StudentAppt` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`StudentID` INT NOT NULL,
	`ApptID` INT NOT NULL,
	PRIMARY KEY (`ID`),
	INDEX `StudentID_idx` (`StudentID` ASC),
	INDEX `ApptID_idx` (`ApptID` ASC),
	CONSTRAINT `StudentID`
		FOREIGN KEY (`StudentID`)
		REFERENCES `Student` (`ID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,    
	CONSTRAINT `ApptID`
		FOREIGN KEY (`ApptID`)
		REFERENCES `Appointment` (`ID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
);